#!/usr/bin/env python3
"""Emit LVGL .c source paths for Makefile/CM7/lvgl.mk (paths relative to Makefile/CM7)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MK_DIR = ROOT / "Makefile" / "CM7"
LVGL_BASE = ROOT / "例程39 压力测试" / "Middlewares" / "LVGL"

SRC_ROOT = LVGL_BASE / "GUI" / "lvgl" / "src"
DEMO_SRC = [
    LVGL_BASE / "GUI_APP" / "demos" / "lv_demos.c",
    LVGL_BASE / "GUI_APP" / "demos" / "stress" / "lv_demo_stress.c",
]
PORT_SRC = [
    ROOT / "BSP" / "LVGL" / "lv_port_disp.c",
    ROOT / "BSP" / "LVGL" / "lv_port_indev.c",
    ROOT / "CM7" / "Core" / "Src" / "lvgl_demo.c",
]

SKIP_PARTS = {
    "examples",
    "tests",
    "test",
    "demos",  # under src if any
}

def should_skip(path: Path) -> bool:
    parts = set(path.parts)
    if "template" in path.name:
        return True
    for p in SKIP_PARTS:
        if p in parts and "GUI_APP" not in parts:
            return True
    return False

def main() -> None:
    sources = []
    for c in sorted(SRC_ROOT.rglob("*.c")):
        if should_skip(c):
            continue
        sources.append(c.relative_to(MK_DIR).as_posix())

    for c in DEMO_SRC + PORT_SRC:
        if c.is_file():
            sources.append(c.relative_to(MK_DIR).as_posix())

    out = MK_DIR / "lvgl.mk"
    lines = [
        "# Auto-generated by tools/collect_lvgl_sources.py",
        f"LVGL_BASE := ../../例程39 压力测试/Middlewares/LVGL",
        "LVGL_SOURCES := \\",
    ]
    for p in sources:
        lines.append(f"  {p} \\")
    lines[-1] = lines[-1].rstrip(" \\")
    lines.append("")
    lines.append("LVGL_INCLUDES := \\")
    lines.append("  -I$(LVGL_BASE)/GUI \\")
    lines.append("  -I$(LVGL_BASE)/GUI/lvgl \\")
    lines.append("  -I$(LVGL_BASE)/GUI/lvgl/examples/porting \\")
    lines.append("  -I$(LVGL_BASE)/GUI_APP/demos \\")
    lines.append("  -I$(LVGL_BASE)/GUI_APP/demos/stress \\")
    lines.append("  -I../../BSP/LVGL")
    lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(sources)} sources to {out}")

if __name__ == "__main__":
    main()
