# LVGL sources/includes (Middlewares/LVGL must exist under project root)
LVGL_BASE := ../../Middlewares/LVGL
LVGL_SOURCES := \
  ../../BSP/LVGL/lv_port_disp.c \
  ../../BSP/LVGL/lv_port_indev.c \
  ../../CM7/Core/Src/lvgl_demo.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_group.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_class.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_draw.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_event.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_id_builtin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_pos.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_property.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_scroll.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_style.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_style_gen.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_obj_tree.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/core/lv_refr.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/display/lv_display.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/dma2d/lv_draw_dma2d.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/dma2d/lv_draw_dma2d_fill.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/dma2d/lv_draw_dma2d_img.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_3d.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_arc.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_buf.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_image.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_label.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_line.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_mask.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_rect.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_triangle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_draw_vector.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/lv_image_decoder.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_arc.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_border.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_fill.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_img.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_layer.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_line.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_stm32_hal.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_triangle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_utils.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/nema_gfx/lv_nema_gfx_path.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/opengles/lv_draw_opengles.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sdl/lv_draw_sdl.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_al88.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888_premultiplied.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_i1.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_l8.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565_swapped.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_arc.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_border.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_fill.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_grad.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_img.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_letter.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_line.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_mask.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_mask_rect.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_transform.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_triangle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_utils.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/draw/sw/lv_draw_sw_vector.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_binfont_loader.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_fmt_txt.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_10.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_12.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_14.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_14_aligned.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_16.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_18.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_20.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_22.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_24.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_26.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_28.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_28_compressed.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_30.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_32.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_34.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_36.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_38.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_40.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_42.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_44.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_46.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_48.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_montserrat_8.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_simsun_14_cjk.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_simsun_16_cjk.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_source_han_sans_sc_14_cjk.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_source_han_sans_sc_16_cjk.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_unscii_16.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/font/lv_font_unscii_8.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/indev/lv_indev.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/indev/lv_indev_gesture.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/indev/lv_indev_scroll.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/layouts/flex/lv_flex.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/layouts/grid/lv_grid.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/layouts/lv_layout.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/barcode/code128.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/barcode/lv_barcode.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/bin_decoder/lv_bin_decoder.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/bmp/lv_bmp.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/expat/xmlparse.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/expat/xmlrole.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/expat/xmltok.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/expat/xmltok_impl.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/expat/xmltok_ns.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/ffmpeg/lv_ffmpeg.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/freetype/lv_freetype.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/freetype/lv_freetype_glyph.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/freetype/lv_freetype_image.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/freetype/lv_freetype_outline.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/freetype/lv_ftsystem.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_cbfs.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_fatfs.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_littlefs.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_memfs.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_posix.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_stdio.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_uefi.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/fsdrv/lv_fs_win32.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/gif/gifdec.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/gif/lv_gif.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/libpng/lv_libpng.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/lodepng/lodepng.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/lodepng/lv_lodepng.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/lz4/lz4.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/qrcode/lv_qrcode.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/qrcode/qrcodegen.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/rle/lv_rle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/rlottie/lv_rlottie.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/svg/lv_svg.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/svg/lv_svg_decoder.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/svg/lv_svg_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/svg/lv_svg_render.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/svg/lv_svg_token.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/tiny_ttf/lv_tiny_ttf.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/tjpgd/lv_tjpgd.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/libs/tjpgd/tjpgd.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/lv_init.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/class/lv_cache_lru_ll.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/class/lv_cache_lru_rb.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/instance/lv_image_cache.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/instance/lv_image_header_cache.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/lv_cache.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/cache/lv_cache_entry.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_anim.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_anim_timeline.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_area.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_array.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_async.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_bidi.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_circle_buf.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_color.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_color_op.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_event.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_fs.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_grad.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_iter.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_ll.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_log.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_lru.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_math.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_matrix.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_palette.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_profiler_builtin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_rb.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_style.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_style_gen.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_templ.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_text.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_text_ap.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_timer.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_tree.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/misc/lv_utils.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_cmsis_rtos2.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_freertos.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_linux.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_mqx.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_os.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_os_none.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_pthread.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_rtthread.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_sdl2.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/osal/lv_windows.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/file_explorer/lv_file_explorer.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/font_manager/lv_font_manager.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/font_manager/lv_font_manager_recycle.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/fragment/lv_fragment.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/fragment/lv_fragment_manager.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/gridnav/lv_gridnav.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/ime/lv_ime_pinyin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/imgfont/lv_imgfont.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/monkey/lv_monkey.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/observer/lv_observer.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/snapshot/lv_snapshot.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/sysmon/lv_sysmon.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/test/lv_test_display.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/test/lv_test_helpers.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/test/lv_test_indev.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/test/lv_test_indev_gesture.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/test/lv_test_screenshot_compare.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/vg_lite_tvg/vg_lite_matrix.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_base_types.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_component.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_style.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_update.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_utils.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/lv_xml_widget.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_arc_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_bar_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_button_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_buttonmatrix_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_calendar_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_canvas_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_chart_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_checkbox_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_dropdown_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_event_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_image_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_keyboard_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_label_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_obj_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_roller_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_scale_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_slider_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_spangroup_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_table_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_tabview_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/others/xml/parsers/lv_xml_textarea_parser.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/builtin/lv_mem_core_builtin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/builtin/lv_sprintf_builtin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/builtin/lv_string_builtin.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/builtin/lv_tlsf.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/clib/lv_mem_core_clib.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/clib/lv_sprintf_clib.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/clib/lv_string_clib.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/lv_mem.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/micropython/lv_mem_core_micropython.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/rtthread/lv_mem_core_rtthread.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/rtthread/lv_sprintf_rtthread.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/rtthread/lv_string_rtthread.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/stdlib/uefi/lv_mem_core_uefi.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/themes/default/lv_theme_default.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/themes/lv_theme.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/themes/mono/lv_theme_mono.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/themes/simple/lv_theme_simple.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/tick/lv_tick.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/3dtexture/lv_3dtexture.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/animimage/lv_animimage.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/arc/lv_arc.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/bar/lv_bar.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/button/lv_button.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/calendar/lv_calendar.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/calendar/lv_calendar_chinese.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/calendar/lv_calendar_header_arrow.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/canvas/lv_canvas.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/chart/lv_chart.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/checkbox/lv_checkbox.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/dropdown/lv_dropdown.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/image/lv_image.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/imagebutton/lv_imagebutton.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/keyboard/lv_keyboard.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/label/lv_label.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/led/lv_led.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/line/lv_line.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/list/lv_list.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/lottie/lv_lottie.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/menu/lv_menu.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/msgbox/lv_msgbox.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/objx_templ/lv_objx_templ.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_animimage_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_dropdown_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_image_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_keyboard_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_label_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_obj_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_roller_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_slider_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_style_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/property/lv_textarea_properties.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/roller/lv_roller.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/scale/lv_scale.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/slider/lv_slider.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/span/lv_span.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/spinbox/lv_spinbox.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/spinner/lv_spinner.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/switch/lv_switch.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/table/lv_table.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/tabview/lv_tabview.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/textarea/lv_textarea.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/tileview/lv_tileview.c \
  ../../Middlewares/LVGL/GUI/lvgl/src/widgets/win/lv_win.c \
  ../../Middlewares/LVGL/GUI_APP/demos/stress/lv_demo_stress.c

LVGL_INCLUDES := \
  -I$(LVGL_BASE)/GUI \
  -I$(LVGL_BASE)/GUI/lvgl \
  -I$(LVGL_BASE)/GUI/lvgl/examples/porting \
  -I$(LVGL_BASE)/GUI_APP/demos/stress \
  -I../../BSP/LVGL
